local printlog = npe_logging.Printlog_npe
local printdebug = npe_logging.Printdebug_npe
local printtrace = npe_logging.Printtrace_npe
local print_table = npe_logging.Print_table_npe
local debug_table = npe_logging.Debug_table_npe
local print_functor = npe_logging.Print_functor_npe
local LOG = npe_logging

------------------------------------------------------------------ NPE EVENT SYSTEM ------------------------------------------------------------------
-- this file list all the functors that can be used to poll the game state for events
-- the functors are used/referenced by the Event prefabs defined in npe script or directly in the npe_modules 
-- the functors are executed by the npe_director to trigger events

-- list of all the events that can be triggered

-- return true if the actor has the given item
function owns_item(item)
    local found = false

	local function check_items(actor,itm)
		local sec = itm:section()
        if sec == item then
            found = true
        end
	end
	db.actor:iterate_inventory(check_items,db.actor)

    return found
end
-- return true if the actor is bleeding
function on_actor_bleeding()
    if db.actor == nil then
        return false
    end
    local bleeding = db.actor.bleeding > 0
    return bleeding
end

-- return true if any actor limbs are damaged
function on_actor_injury()

    if not zzz_player_injuries then return false end

	local is_serious_injury = false
	
	if zzz_player_injuries.health.head < 18 or zzz_player_injuries.health.torso < 18 or zzz_player_injuries.health.rightarm < 7 or zzz_player_injuries.health.leftarm < 7 or zzz_player_injuries.health.rightleg < 7 or zzz_player_injuries.health.leftleg < 7 then
		is_serious_injury = true
	end

	return is_serious_injury
end

-- return true if the actor limbs are damaged
function on_actor_limb_broken()
    if db.actor == nil then
        return false
    end
    if not zzz_player_injuries then return false end

    local is_limb_broken = false
	if zzz_player_injuries.health.head == 0 or zzz_player_injuries.health.torso == 0 or zzz_player_injuries.health.rightarm == 0 or zzz_player_injuries.health.leftarm == 0 or zzz_player_injuries.health.rightleg == 0 or zzz_player_injuries.health.leftleg == 0 then
		is_limb_broken = true
	end    

    return is_limb_broken
end

-- return true if the actor is irradiated
function on_actor_irradiated()
    if db.actor == nil then
        return false
    end
    local irradiated = db.actor.radiation > 0
    return irradiated
end
-- return true if the actor is stressed
function on_actor_stressed()
    if db.actor == nil then
        return false
    end
    local stressed = db.actor.psy_health < 0.9
    return stressed
end
-- return true if the actor is experiencing madness
function on_actor_mad()
    if db.actor == nil then
        return false
    end
    local madness = db.actor.psy_health < 0.5
    return madness
end
-- return true if the actor is hungry
function on_actor_hungry()
    local hungry = actor_status.get_satienty(true) > 0
    return hungry
end
-- return true if the actor is overweight
function on_actor_overweight()
    local overweight = actor_status.get_overweight(true) > 0
    return overweight
end

function on_actor_thirsty()
    -- local thirsty = actor_status.get_thirst(true) > 0
    -- return thirsty
    return false
end

-- returns true if set has been played, completed
function on_set_completed(module, set_id)
    return  npe_mcm.npe_module_get_setting(module, set_id)
end
-- returns true if all sets have been played, completed
function on_sets_completed(module, set_id_table)
    for _, set_id in ipairs(set_id_table) do
        if not on_set_completed(module, set_id) then
            return false
        end
    end
    return true
end
-- return true if the actor is on a task
function is_on_task(task)
    printtrace(LOG.INFO, LOG.EVENT," looking for task " .. task)
    local has_task = false
    task_manager.task_ini:section_for_each(function(task_id)
        if db.actor:get_task(task_id, true) and task_id == task then
            printtrace(LOG.INFO, LOG.EVENT," found task " .. task_id)
            has_task = true
        end
      end)
    return has_task
end

-- return true if the actor is near a smart terrain with the given name
local default_limit_distance = 50
function on_near_smart_terrain(smart_name, near_distance)
    if near_distance == nil then
        near_distance = default_limit_distance
    end
    local id = smart_terrain.nearest_to_actor_smart.id
    
    local smart = id and alife_object(id)
    if smart and smart:name() == smart_name then
        local dist = smart and smart.position:distance_to(db.actor:position())
        printtrace(LOG.INFO, LOG.EVENT," looking for smart " .. smart_name .. ", found " .. smart:name() .. " at distance" .. dist .. ", limit " .. near_distance)
        if dist and dist < near_distance then
            return true
        end
    end    
    return false
end

-- return true if the actor is near a game object with the id
local default_limit_distance = 5
function on_near_game_object(id, near_distance)
    if near_distance == nil then
        near_distance = default_limit_distance
    end
    printtrace(LOG.INFO, LOG.EVENT," looking for game object " .. id .. " at distance " .. near_distance)
    local se_obj = id and alife_object(id)
    if (not se_obj) or not (se_obj and se_obj.online) then 
        printlog(LOG.ERROR, LOG.EVENT," game_object does not exist or is not online")
        return 
    end
    local szpos = se_obj.position
    local dist = szpos:distance_to(db.actor:position()) or 0
    printtrace(LOG.INFO, LOG.EVENT," distance to game object " .. id .. " is " .. dist)
    if dist <= near_distance then
        return true
    else
        return false
    end
end

-- general monkey patching

-- saves the last npc talked to
Last_npc_talked = nil
local who_is_npc_mp = dialogs.who_is_npc
function dialogs.who_is_npc(first_speaker, second_speaker)
    local npc = who_is_npc_mp(first_speaker, second_speaker)
    npe_events.Last_npc_talked = npc:character_name()
    printtrace(LOG.INFO, LOG.EVENT, "Last_npc_talked = " .. tostring(npe_events.Last_npc_talked))
	return npc
end

function IsInvOwner(npc)
-- We need this cause Sid and Forester are not NPCs
	return IsStalker(npc)
end

function parse_blackmarket_inventory(npc, possible_kind)

	local found = false
	local sec, kind
	local function iterate(owner,obj)
		sec = obj:section()
        -- printdebug(LOG.INFO, LOG.EVENT," - name %s sec %s",obj:name(), sec )
        if possible_kind then
            kind = SYS_GetParam(0,sec,"kind") or "na"
            if ignore_kind or pkind["s_all"] or pkind[kind] then
                found = true
                return
            end            
        else
            if IsWeapon(obj) then
                printdebug(LOG.INFO, LOG.EVENT," name %s sec %s",obj:name(), sec )
                found = true
                return
            end
        end
	end
	if IsInvOwner(npc) then
        printdebug(LOG.INFO, LOG.EVENT," npc IsInvOwner")
        npc:iterate_inventory(iterate,nil)
	end
	
	return found
end

function on_npc_mechanic()
    -- trade_generic_mechanic
end

function on_npc_trader()
    local npc = mob_trade.GetTalkingNpc()  -- db.actor:get_talking_npc()
    local is_trader = npc and trade_manager.get_trade_profile(npc:id(), "cfg_ltx")
    printdebug(LOG.INFO, LOG.EVENT," on_npc_trader %s", is_trader)
    if not is_trader then return end        -- if not trader  
    
    if string.find(is_trader,"trade_generic.ltx") then 
        return false
    else return string.find(is_trader,"trade_%a+") end
end

function on_npc_blackmarket_trader()
    local npc = mob_trade.GetTalkingNpc()  -- db.actor:get_talking_npc()
    printdebug(LOG.INFO, LOG.EVENT," on_npc_blackmarket_trader")
    local is_trader = on_npc_trader(npc)
    if not is_trader then return end        -- if not trader  

    return parse_blackmarket_inventory(npc)
end

function on_npc_barman()
    -- trade_generic_barman
end

function on_npc_medic()
    -- trade_generic_medic
end

function on_npc_stalker()
    -- trade_generic.ltx
end

-- for debugging monkey patching
local function actor_on_update()
    -- printdebug(LOG.INFO, LOG.EVENT," Last_npc_talked = " .. tostring(Last_npc_talked))

    -- if on_near_smart_terrain(SMART_TERRAIN.cordon_loners_base) then
    --     printdebug(LOG.INFO, LOG.EVENT," Near cordon_loners_base ")
    -- end
    -- if on_near_smart_terrain(SMART_TERRAIN.cordon_military_base) then
    --     printdebug(LOG.INFO, LOG.EVENT," Near cordon_military_base ")
    -- end
    -- if smart_terrain.nearest_to_actor_smart.id then
    --     local id = smart_terrain.nearest_to_actor_smart.id
    --     printdebug(LOG.INFO, LOG.EVENT," Near smart terrain " .. smart_terrain.nearest_to_actor_smart.id)
    --     local smart = id and alife_object(id)
    --     if smart and smart:name() then
    --         printdebug(LOG.INFO, LOG.EVENT," Near smart terrain " .. smart:name())
    --     end
    -- end

    -- if npe_is_on_task(TASK.fanatic_training_day_boar_hunting) then
    --     printdebug(LOG.INFO, LOG.EVENT," On task Training Day: Boar Hunting")
    -- end
    
end


function on_game_start()
    RegisterScriptCallback("actor_on_update", actor_on_update)
end